version: 2.1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - static-code-analysis
      - run-unit-test:
          requires:
            - static-code-analysis
#      - build-docker-image
#      - deploy-to-staging
#      - deploy-to-prod

jobs:
  static-code-analysis:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: Check sytle
          command: |
            echo "check style"
      - run:
          name: Check dependencies
          command: |
            echo "check dependencies"
  run-unit-test:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: Run test and verify test coverage
          command: |
            ./gradlew test